### ISSUE TITLE
Setting Prog key to SYSTER makes Syster active after programming

### ISSUE THREAD

**Issue by ilianaw** [keyboardio/Kaleidoscope-Syster#3]
I'm filing this issue here because it's where the symptom is showing up, but this might be a bug at a lower level...

When I have my Prog key on the Model 01 set to SYSTER and I reprogram the keyboard, the keyboard comes up in SYSTER mode. This seems wrong, as when the keyboard boots I am not pressing down the Prog key.

I've verified that this doesn't happen if I move SYSTER to another key.

**Comment by algernon** [comment]
Just one question, so that I can localize the problem better: If you map `PROG` to, say `Key_A`, do you get `a` input when the keyboard boots back up? Or, perhaps a better check would be a `LockLayer()` mapping, to see if the keyboard locks to that layer on boot (and a `Key_NoKey` on the target layer there, to avoid flipping there and back)...

**Comment by algernon** [comment]
For the record, my original assumption was that the `PROG` key is still held during boot, which would have explained the situation nicely. But @ilianaw told me she releases the key before the LEDs stop chasing around during flash, which invalidates that assumption.

The next idea is that while flashing, the ATTiny in the other half is still doing scans, and when the main MCU boots, it gets an obsolete scan report first. This would explain the symptoms, but I feel this is quite a stretch.

@obra, do you have any insight perhaps? Whether the above idea is even worth exploring, or if it is completely wrong?

**Comment by ilianaw** [comment]
> If you map `PROG` to, say `Key_A`, do you get `a` input when the keyboard boots back up?

I do not.

**Comment by algernon** [comment]
Darn. That'll complicate matters a bit.

**Comment by ilianaw** [comment]
The workaround you suggested for me works like a charm. For reference, what I'm currently running is at https://github.com/ilianaw/Model01-Firmware/blob/a4cfdee303a6020ab0e9c840c7431b619304ad18/Model01-Firmware.ino

**Comment by algernon** [comment]
Oooh. I *think* I may know what happens: [this line](https://github.com/keyboardio/Kaleidoscope/blob/086b16f4dfca9a75ef75df77a06688ce323763bf/src/Kaleidoscope.cpp#L21) triggers an event handler run, which, through a series of unfortunate circumstances may activate Syster too. I can't (yet?) see how, but this is another possibility. One that would also explain why `Key_A` does not exhibit a similar issue.

If you don't mind trying a few more things, can I ask you to check if mapping `PROG` to a `OneShot` key activates one-shot mode?

**Comment by ilianaw** [comment]
(I'll try this evening — need to head out for the day, I've had far too much fun with my keyboard this morning. 😅)

**Comment by gedankenexperimenter** [comment]
Here's an uneducated guess: maybe [this line](https://github.com/keyboardio/Kaleidoscope-Syster/blob/f4ffac57f8c39a19336b53d26477bd367805cd7e/src/Kaleidoscope/Syster.cpp#L29) should initialize the variable?

**Comment by algernon** [comment]
Nah, it is static, and as such, initialized to zero (false) by default.

**Comment by ilianaw** [comment]
I applied the following changes to my firmware (https://github.com/ilianaw/Model01-Firmware/commit/14ea011134a315d7787e671682034ecfd7e44e2b):

```diff
diff --git a/Model01-Firmware.ino b/Model01-Firmware.ino
index 913137b..2eafa4e 100644
--- a/Model01-Firmware.ino
+++ b/Model01-Firmware.ino
@@ -14,6 +14,7 @@
 #include "Kaleidoscope-Focus.h"
 #include "Kaleidoscope-Unicode.h"
 #include "Kaleidoscope-Syster.h"
+#include "Kaleidoscope-OneShot.h"
 #include "Kaleidoscope-HostPowerManagement.h"
 #include "Kaleidoscope-PrefixLayer.h"
 
@@ -36,7 +37,7 @@ static const kaleidoscope::PrefixLayer::dict_t prefixlayerdict[] PROGMEM = PREFI
 KEYMAPS(
 
   [QWERTY] = KEYMAP_STACKED
-  (SYSTER,       Key_1, Key_2, Key_3, Key_4, Key_5, Key_LEDEffectNext,
+  (OSL(FUNCTION),Key_1, Key_2, Key_3, Key_4, Key_5, Key_LEDEffectNext,
    Key_Backtick, Key_Q, Key_W, Key_E, Key_R, Key_T, Key_Tab,
    Key_PageUp,   Key_A, Key_S, Key_D, Key_F, Key_G,
    Key_PageDown, Key_Z, Key_X, Key_C, Key_V, Key_B, Key_Escape,
@@ -197,16 +198,11 @@ void setup() {
     &Macros,
     &Focus,
     &Unicode,
+    &OneShot,
     &HostPowerManagement,
     &PrefixLayer
   );
 
-  /*
-   * FIXME: Work around for https://github.com/keyboardio/Kaleidoscope-Syster/issues/3
-   * https://trunk.mad-scientist.club/@algernon/99518558666830872
-   */
-  KeyboardHardware.maskKey(0, 0);
-
   HostOS.os(kaleidoscope::hostos::LINUX);
 
   Focus.addHook(FOCUS_HOOK_HOSTOS);
```

OneShot is not activated on reflash, and appears to be working normally otherwise.

**Comment by algernon** [comment]
Sweet, that narrows things down. Thank you!

**Comment by algernon** [comment]
Mananged to reproduce this, finally!

**Comment by algernon** [comment]
Turns out, this is an issue at a deeper level: it seems that if we release the `PROG` key after the board reset, it will trigger a keydown & keyup event once the firmware boots. I'm seeing two events coming from `0,0` in this case. `OneShot` sees this too, and it activates as well, but because it has a timeout, by the time you check if it is active, it likely deactivates.

The proper solution here would likely involve running a key scan in `Kaleidoscope.setup()`, and masking out `0,0` if it is set.

**Comment by algernon** [comment]
Talking with @obra convinced me that my proposed fix would be too broad, and break use-cases more common than putting `Syster` (or similar keys) on `Prog`. Therefore the workaround I suggested earlier, namely, putting `KeyboardHardware.maskKey(0, 0);` in one's `setup()` mehod is the most correct fix at the moment.

(The issue is not specific to `Syster` by the way, it just so happens that it is much more noticeable with it.)
